# Generated by Django 4.2.7 on 2023-11-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tasks',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
