# Generated by Django 4.2.7 on 2023-11-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_tasks_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tasks',
            name='created_at',
            field=models.DateField(),
        ),
    ]
