# Generated by Django 4.2.7 on 2023-11-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_tasks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tasks',
            name='task_describtion',
            field=models.CharField(max_length=500),
        ),
    ]
